---
- name: install rsync
  yum:
    name: rsync
    state: present

- name: create subdirectories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /srv/southbridge

- name: sync ds files
  synchronize:
    src: "ds/"
    dest: "/srv/southbridge/"
    owner: no
    group: no
    perms: yes
    use_ssh_args: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
      - "--omit-dir-times"
      - "--chmod=D0755"
  when: server_type == 'ds'

- name: sync vs files
  synchronize:
    src: "vs/"
    dest: "/srv/southbridge/"
    owner: no
    group: no
    perms: yes
    use_ssh_args: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
      - "--omit-dir-times"
      - "--chmod=D0755"
  when: ( server_type == 'vs' ) or ( server_type == 'vds')
...
