- set_fact: php_version_defined="{{php_version is defined}}"

- name: install httpd and tools
  become: true
  yum:
    name: "{{ item }}"
    enablerepo: southbridge-stable
    state: present
  with_items:
    - httpd
    - httpd-tools
    - logrotate

- name: install mod_ruid2
  become: true
  yum:
    name: mod_ruid2
    state: present

- name: install mod_rpaf
  become: true
  yum:
    name: mod_rpaf
    enablerepo: southbridge-stable
    state: present
  when: ansible_distribution_major_version <= '6'
  notify: restart httpd

- name: create subdirectories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - /etc/httpd/vhosts.d
    - /var/log/httpd
    - /srv/southbridge/bin
    - /srv/southbridge/etc
    - /srv/southbridge/skel
    - /etc/monit.d

- name: create www/.ssh subdirectory
  become: true
  file:
    path: /var/www/.ssh
    state: directory
    owner: apache
    group: apache
    mode: 0700

- name: copy configs
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'etc/httpd/conf.d/proxy_ajp.conf',
        dest: '/etc/httpd/conf.d/proxy_ajp.conf',
        mode: '0644' }
    - { src: 'etc/httpd/conf/httpd.conf.rhel{{ansible_distribution_major_version}}',
        dest: '/etc/httpd/conf/httpd.conf',
        mode: '0644' }
    - { src: 'etc/httpd/conf.d/mod_rpaf.conf',
        dest: '/etc/httpd/conf.d/mod_rpaf.conf',
        mode: '0644' }
    - { src: 'etc/httpd/conf.d/server.conf',
        dest: '/etc/httpd/conf.d/server.conf',
        mode: '0644' }
    - { src: 'etc/httpd/conf.d/vhosts.conf',
        dest: '/etc/httpd/conf.d/vhosts.conf',
        mode: '0644' }
    - { src: 'etc/httpd/conf.d/remoteip.conf',
        dest: '/etc/httpd/conf.d/remoteip.conf',
        mode: '0644' }
  notify: restart httpd

- name: copy configs monit
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'etc/monit.d/httpd',
        dest: '/etc/monit.d/httpd',
        mode: '0644' }
    - { src: 'etc/monit.d/httpd-segfaults',
        dest: '/etc/monit.d/httpd-segfaults',
        mode: '0644' }
  notify: restart monit

- name: install role files.shared
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'srv/southbridge/bin/admin-bitrix-shared.sh',
        dest: '/srv/southbridge/bin/admin-bitrix-shared.sh',
        mode: '0755' }
    - { src: 'srv/southbridge/bin/admin-shared.sh',
        dest: '/srv/southbridge/bin/admin-shared.sh',
        mode: '0755' }
    - { src: 'srv/southbridge/skel/apache24-vhost-bitrix-shared.tpl.dist',
        dest: '/srv/southbridge/skel/apache24-vhost-bitrix-shared.tpl.dist',
        mode: '0644' }
    - { src: 'srv/southbridge/skel/apache24-vhost-shared.tpl.dist',
        dest: '/srv/southbridge/skel/apache24-vhost-shared.tpl.dist',
        mode: '0644' }
    - { src: 'srv/southbridge/skel/apache-vhost-bitrix-shared.tpl.dist',
        dest: '/srv/southbridge/skel/apache-vhost-bitrix-shared.tpl.dist',
        mode: '0644' }
    - { src: 'srv/southbridge/skel/apache-vhost-shared.tpl.dist',
        dest: '/srv/southbridge/skel/apache-vhost-shared.tpl.dist',
        mode: '0644' }
    - { src: 'srv/southbridge/skel/php-fpm-pool-shared.tpl.dist',
        dest: '/srv/southbridge/skel/php-fpm-pool-shared.tpl.dist',
        mode: '0644' }
    - { src: 'srv/southbridge/skel/phpfpm-vhost-bitrix-shared.tpl.dist',
        dest: '/srv/southbridge/skel/phpfpm-vhost-bitrix-shared.tpl.dist',
        mode: '0644' }

- name: install Apache DOS protect
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'etc/cron.d/apache_dos_protect',
        dest: '/etc/cron.d/apache_dos_protect',
        mode: '0644' }
    - { src: 'etc/logrotate.d/apache_dos_protect',
        dest: '/etc/logrotate.d/apache_dos_protect',
        mode: '0644' }
    - { src: 'srv/southbridge/bin/apache_dos_protect.sh',
        dest: '/srv/southbridge/bin/apache_dos_protect.sh',
        mode: '0755' }
    - { src: 'srv/southbridge/etc/apache_dos_protect.conf.dist',
        dest: '/srv/southbridge/etc/apache_dos_protect.conf.dist',
        mode: '0644' }
  when: httpd_dos_protect

- name: enable httpd service
  become: true
  service:
    name: httpd
    enabled: true

- name: include php role
  include_role:
    name: php
  when: php_version_defined
